using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HermesProxy.World.Enums
{
    public enum ItemModifier
    {
        TransmogAppearanceAllSpecs = 0,
        TransmogAppearanceSpec1 = 1,
        UpgradeId = 2,
        BattlePetSpeciesId = 3,
        BattlePetBreedData = 4, // (Breedid) | (Breedquality << 24)
        BattlePetLevel = 5,
        BattlePetDisplayId = 6,
        EnchantIllusionAllSpecs = 7,
        ArtifactAppearanceId = 8,
        TimewalkerLevel = 9,
        EnchantIllusionSpec1 = 10,
        TransmogAppearanceSpec2 = 11,
        EnchantIllusionSpec2 = 12,
        TransmogAppearanceSpec3 = 13,
        EnchantIllusionSpec3 = 14,
        TransmogAppearanceSpec4 = 15,
        EnchantIllusionSpec4 = 16,
        ChallengeMapChallengeModeId = 17,
        ChallengeKeystoneLevel = 18,
        ChallengeKeystoneAffixId1 = 19,
        ChallengeKeystoneAffixId2 = 20,
        ChallengeKeystoneAffixId3 = 21,
        ChallengeKeystoneAffixId4 = 22,
        ArtifactKnowledgeLevel = 23,
        ArtifactTier = 24,
        TransmogAppearanceSpec5 = 25,
        PvpRating = 26,
        EnchantIllusionSpec5 = 27,
        ContentTuningId = 28,
        ChangeModifiedCraftingStat1 = 29,
        ChangeModifiedCraftingStat2 = 30,
        TransmogSecondaryAppearanceAllSpecs = 31,
        TransmogSecondaryAppearanceSpec1 = 32,
        TransmogSecondaryAppearanceSpec2 = 33,
        TransmogSecondaryAppearanceSpec3 = 34,
        TransmogSecondaryAppearanceSpec4 = 35,
        TransmogSecondaryAppearanceSpec5 = 36,
        SoulbindConduitRank = 37,

        Max
    }

    public enum ItemContext : byte
    {
        None = 0,
        DungeonNormal = 1,
        DungeonHeroic = 2,
        RaidNormal = 3,
        RaidRaidFinder = 4,
        RaidHeroic = 5,
        RaidMythic = 6,
        PvpUnranked1 = 7,
        PvpRanked1Unrated = 8,
        ScenarioNormal = 9,
        ScenarioHeroic = 10,
        QuestReward = 11,
        InGameStore = 12,
        TradeSkill = 13,
        Vendor = 14,
        BlackMarket = 15,
        MythicplusEndOfRun = 16,
        DungeonLvlUp1 = 17,
        DungeonLvlUp2 = 18,
        DungeonLvlUp3 = 19,
        DungeonLvlUp4 = 20,
        ForceToNone = 21,
        Timewalking = 22,
        DungeonMythic = 23,
        PvpHonorReward = 24,
        WorldQuest1 = 25,
        WorldQuest2 = 26,
        WorldQuest3 = 27,
        WorldQuest4 = 28,
        WorldQuest5 = 29,
        WorldQuest6 = 30,
        MissionReward1 = 31,
        MissionReward2 = 32,
        MythicplusEndOfRunTimeChest = 33,
        ZzchallengeMode3 = 34,
        MythicplusJackpot = 35,
        WorldQuest7 = 36,
        WorldQuest8 = 37,
        PvpRanked2Combatant = 38,
        PvpRanked3Challenger = 39,
        PvpRanked4Rival = 40,
        PvpUnranked2 = 41,
        WorldQuest9 = 42,
        WorldQuest10 = 43,
        PvpRanked5Duelist = 44,
        PvpRanked6Elite = 45,
        PvpRanked7 = 46,
        PvpUnranked3 = 47,
        PvpUnranked4 = 48,
        PvpUnranked5 = 49,
        PvpUnranked6 = 50,
        PvpUnranked7 = 51,
        PvpRanked8 = 52,
        WorldQuest11 = 53,
        WorldQuest12 = 54,
        WorldQuest13 = 55,
        PvpRankedJackpot = 56,
        TournamentRealm = 57,
        Relinquished = 58,
        LegendaryForge = 59,
        QuestBonusLoot = 60,
        CharacterBoostBfa = 61,
        CharacterBoostShadowlands = 62,
        LegendaryCrafting1 = 63,
        LegendaryCrafting2 = 64,
        LegendaryCrafting3 = 65,
        LegendaryCrafting4 = 66,
        LegendaryCrafting5 = 67,
        LegendaryCrafting6 = 68,
        LegendaryCrafting7 = 69,
        LegendaryCrafting8 = 70,
        LegendaryCrafting9 = 71,
        WeeklyRewardsAdditional = 72,
        WeeklyRewardsConcession = 73,
        WorldQuestJackpot = 74,
        NewCharacter = 75,
        WarMode = 76,
        PvpBrawl1 = 77,
        PvpBrawl2 = 78,
        Torghast = 79,
        CorpseRecovery = 80,
        WorldBoss = 81,
        RaidNormalExtended = 82,
        RaidRaidFinderExtended = 83,
        RaidHeroicExtended = 84,
        RaidMythicExtended = 85,
        CharacterTemplate91 = 86,

        Max
    }

    public enum ItemVendorType
    {
        None     = 0,
        Item     = 1,
        Currency = 2,
        Spell    = 3,
        MawPower = 4
    }

    public enum BuyResult
    {
        CantFindItem      = 0,
        ItemAlreadySold   = 1,
        NotEnoughtMoney   = 2,
        SellerDontLikeYou = 4,
        DistanceTooFar    = 5,
        ItemSoldOut       = 7,
        CantCarryMore     = 8,
        RankRequire       = 11,
        ReputationRequire = 12
    }
}
